### ISSUE TITLE
安卓手机环境下壁纸设置失败了。

### ISSUE THREAD

**Issue by chenwenxian** [dcloudio/uni-template-picture#2]

**Comment by Wangyaqi** [comment]
已经修复，感谢反馈 [https://github.com/dcloudio/uni-template-picture/commit/9791b80ea69d1bf29650c1ca0c21da9ee0f73361](https://github.com/dcloudio/uni-template-picture/commit/9791b80ea69d1bf29650c1ca0c21da9ee0f73361)

**Comment by chenwenxian** [comment]
我重新下载测试下。
